version: '3.7'
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    hostname: gitea
    restart: unless-stopped
    ports:
      - "2222:2222"
    volumes:
      - ../Data/gitea:/data
    environment:
      - RUN_MODE=prod
      - DOMAIN=localhost
      - SSH_PORT=2222
      - SSH_LISTEN_PORT=2222
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=changeme
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true
      - USER_UID=1000
      - USER_GID=1000
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.gitea.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.gitea.entrypoints=web-secure"
      - "traefik.http.routers.gitea.service=gitea"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000" # Proxied Port
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ../Data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gitea
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=changeme
